version: '3.9'

services:
  zookeeper:
    extends:
      service: zookeeper
      file: ../docker-compose.yaml
    networks:
      - asap-kafka
  
  kafka:
    extends:
      service: kafka
      file: ../docker-compose.yaml
    volumes:
      - kafka-data:/kafka
    networks:
      - asap-kafka
    ports:
      - '8001:9092'
    environment:
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:8001,INTERNAL://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
        
  kafka-ui:
    extends:
      service: kafka-ui
      file: ../docker-compose.yaml
    networks:
      - asap-kafka
    ports:
      - "8003:8080"
    volumes:
      - ../../protos:/schemas
      - ../kafka-ui-config.yaml:/config.yaml
    environment:
      kafka.clusters.0.bootstrapServers: kafka:9094

networks:
  asap-kafka:
    driver: bridge

volumes:
  kafka-data:
