version: '3.9'

services:
  
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - asap-kafka

  kafka:
    image: 'wurstmeister/kafka:latest'
    restart: unless-stopped
    environment:
      KAFKA_LOG_DIRS: /kafka-data
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: >
        asap_queue_updated:1:1,
        asap_subject_course:1:1,
        asap_subject_course_points:1:1,
        asap_assignment:1:1,
        asap_student_points:1:1,
        asap_submission_data:1:1,
        asap_ban_machine_analysis:1:1
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9094
        KAFKA_ADVERTISED_LISTENERS: EXTERNAL://127.0.0.1:8001,INTERNAL://kafka:9094
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
        ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    volumes:
      - kafka-data:/kafka-data
    networks:
      - asap-kafka
    ports:
      - '8001:9092'

  kafka-ui:
    depends_on:
      - kafka
    extends:
      service: kafka-ui
      file: ../docker-compose.yaml
    networks:
      - asap-kafka
    ports:
      - "8003:8080"
    volumes:
      - ../../protos:/schemas
    environment:
      kafka.clusters.0.bootstrapServers: kafka:9094

networks:
  asap-kafka:
    driver: bridge

volumes:
  kafka-data:
