version: '3.9'

services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'wurstmeister/kafka:latest'
    restart: unless-stopped
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: >
        asap_queue_updated:1:1,
        asap_subject_course:1:1,
        asap_subject_course_points:1:1,
        asap_assignment:1:1
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      SPRING_CONFIG_ADDITIONAL-LOCATION: /config.yaml
