version: '3.9'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    environment:
      kafka.clusters.0.name: kafka

      kafka.clusters.0.serde.0.name: ProtobufFile
      kafka.clusters.0.serde.0.properties.protobufFilesDir: /schemas/

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.asap_queue_updated: itmo.dev.asap.kafka.QueueUpdatedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.asap_queue_updated: itmo.dev.asap.kafka.QueueUpdatedValue

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.asap_subject_course: itmo.dev.asap.kafka.SubjectCourseCreatedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.asap_subject_course: itmo.dev.asap.kafka.SubjectCourseCreatedValue

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.asap_subject_course_points: itmo.dev.asap.kafka.SubjectCoursePointsUpdatedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.asap_subject_course_points: itmo.dev.asap.kafka.SubjectCoursePointsUpdatedValue

      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.asap_assignment: itmo.dev.asap.kafka.AssignmentCreatedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.asap_assignment: itmo.dev.asap.kafka.AssignmentCreatedValue
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.asap_student_points: itmo.dev.asap.kafka.StudentPointsUpdatedKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.asap_student_points: itmo.dev.asap.kafka.StudentPointsUpdatedValue
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.asap_submission_data: itmo.dev.asap.kafka.SubmissionDataKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.asap_submission_data: itmo.dev.asap.kafka.SubmissionDataValue
      
      kafka.clusters.0.serde.0.properties.protobufMessageNameForKeyByTopic.asap_ban_machine_analysis: itmo.dev.asap.kafka.BanMachineAnalysisKey
      kafka.clusters.0.serde.0.properties.protobufMessageNameByTopic.asap_ban_machine_analysis: itmo.dev.asap.kafka.BanMachineAnalysisValue