version: '3.9'

services:
  kafka-ui:
    extends:
      service: kafka-ui
      file: ../docker-compose.yaml
    volumes:
      - ../../protos:/schemas
      - ./certificates:/certificates
    environment:
      server.forward-headers-strategy: FRAMEWORK
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
      kafka.clusters.0.bootstrapServers: ${KAFKA_HOST}
      kafka.clusters.0.properties.security.protocol: SASL_SSL
      kafka.clusters.0.properties.sasl.mechanism: SCRAM-SHA-512
      kafka.clusters.0.properties.sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username=${KAFKA_USERNAME} password=${KAFKA_PASSWORD};
      kafka.clusters.0.properties.ssl.ca.location: /certificates/certificate.crt