version: '3.9'

services:
  kafka-ui:
    extends:
      service: kafka-ui
      file: ../docker-compose.yaml
    volumes:
      - ../../protos:/schemas
    environment:
      server.forward-headers-strategy: FRAMEWORK
      SERVER_SERVLET_CONTEXT_PATH: /kafka-ui
      kafka.clusters.0.bootstrapServers: ${KAFKA_HOST}